### ISSUE TITLE
can't find any of my pastes..

### ISSUE THREAD

**Issue by dstN** [wKovacs64/pwned#2] opened 2017-05-05 23:22 UTC
if i search for your example "nobody@nowhere.com" it does work. but if i search for my email addresses it's not working - any clue why?

**Comment by wKovacs64** [comment] 2017-05-06 22:36
Hey @dstN!

Some questions that will help us figure out what's going on:

* What is the full command line that you're using?
* Can you clarify what you mean by "not working"? Does it error, or produce unexpected results?
* Does [the website](https://haveibeenpwned.com) work for the same address you're trying on the command line?

If you'd like to share the email address that isn't working, I'd be happy to help troubleshoot on my end as well.

**Comment by wKovacs64** [comment] 2017-05-22 21:58
Closing for now, as I cannot reproduce the issue. We can reopen if you'd like to provide the requested information for additional troubleshooting if this is still a problem.

**Closed by wKovacs64** 2017-05-22 21:58 UTC
Labels: awaiting user response, could not reproduce

**Comment by christopheranderton** [comment] 2017-09-01 16:00
I don't know, but i think he may thinking of this:

 `pwned ba nobody@nowhere.com` 
  will get results.

 `pwned pa nobody@nowhere.com` 
  will result in (if it's not found in any pastes): 
`Good news — no pwnage found!`

So, i think it's only a slight confusion about pastes, and what it is.

**Comment by dstN** [comment] 2017-09-15 15:38
sadly i don't remember anymore. damn, i have to check my github more often. sorry!
